"""empty message

Revision ID: 0826eb2a6f4c
Revises: bf0b3e6ba00f
Create Date: 2019-11-07 23:55:20.512417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0826eb2a6f4c'
down_revision = 'bf0b3e6ba00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    # ### end Alembic commands ###
