"""empty message

Revision ID: bf0b3e6ba00f
Revises: 0d8148b05d8f
Create Date: 2019-11-07 23:44:39.136159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0b3e6ba00f'
down_revision = '0d8148b05d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('good_quantity', sa.Integer(), nullable=False))
    op.add_column('goods', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'price')
    op.drop_column('carts', 'good_quantity')
    # ### end Alembic commands ###
